package contracts

// This file is auto-generated by helpers/write_contract_addresses.sh
// Do not edit manually - run the script to regenerate
// Generated from commit: c039a2129683752e3112b7083099d65a2367f53d

// Network constants
const (
	SepoliaNetwork = "sepolia"
	UzhNetwork     = "uzh"
	MainnetNetwork = "mainnet"
)

// Contract name constants
const (
	ProcessRegistryContract                = "processRegistry"
	OrganizationRegistryContract           = "organizationRegistry"
	StateTransitionVerifierGroth16Contract = "stateTransitionVerifierGroth16"
	ResultsVerifierGroth16Contract         = "resultsVerifierGroth16"
	SequencerRegistryContract              = "sequencerRegistry"
)

// Contract addresses by network
const (
	OrganizationRegistryMainnetAddress = "0x0"
	OrganizationRegistrySepoliaAddress = "0xe7136ED5a7b0e995A8fe35d8B1B815E4160cB491"
	OrganizationRegistryUzhAddress = "0xf7BCE4546805547bE526Ca864d6722Ed193E51Aa"
	ProcessRegistryMainnetAddress = "0x0"
	ProcessRegistrySepoliaAddress = "0x40939Ec9FD872eb79A1723B559572dfD71a05d11"
	ProcessRegistryUzhAddress = "0x69B16f67Bd2fB18bD720379E9C1Ef5EaD3872d67"
	ResultsVerifierGroth16MainnetAddress = "0x0"
	ResultsVerifierGroth16SepoliaAddress = "0x1188cEbB56ecc90e2bAe5c914274C81Fe1a22e67"
	ResultsVerifierGroth16UzhAddress = "0x00c7F87731346F592197E49A90Ad6EC236Ad9985"
	SequencerRegistryMainnetAddress = "0x0"
	SequencerRegistrySepoliaAddress = "0x0"
	SequencerRegistryUzhAddress = "0x0"
	StateTransitionVerifierGroth16MainnetAddress = "0x0"
	StateTransitionVerifierGroth16SepoliaAddress = "0xb7A142D24b9220eCBC4f7fcB89Ee952a6C7E332a"
	StateTransitionVerifierGroth16UzhAddress = "0x5e4673CD378F05cc3Ae25804539c91E711548741"
)

// GetContractAddress returns the address for a given contract and network
func GetContractAddress(contract, network string) string {
	switch contract {
	case ProcessRegistryContract:
		switch network {
		case SepoliaNetwork:
			return ProcessRegistrySepoliaAddress
		case UzhNetwork:
			return ProcessRegistryUzhAddress
		case MainnetNetwork:
			return ProcessRegistryMainnetAddress
		}
	case OrganizationRegistryContract:
		switch network {
		case SepoliaNetwork:
			return OrganizationRegistrySepoliaAddress
		case UzhNetwork:
			return OrganizationRegistryUzhAddress
		case MainnetNetwork:
			return OrganizationRegistryMainnetAddress
		}
	case StateTransitionVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return StateTransitionVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return StateTransitionVerifierGroth16UzhAddress
		case MainnetNetwork:
			return StateTransitionVerifierGroth16MainnetAddress
		}
	case ResultsVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return ResultsVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return ResultsVerifierGroth16UzhAddress
		case MainnetNetwork:
			return ResultsVerifierGroth16MainnetAddress
		}
	case SequencerRegistryContract:
		switch network {
		case SepoliaNetwork:
			return SequencerRegistrySepoliaAddress
		case UzhNetwork:
			return SequencerRegistryUzhAddress
		case MainnetNetwork:
			return SequencerRegistryMainnetAddress
		}
	}
	return ""
}

// GetAllContractAddresses returns a map of all contract addresses for a given network
func GetAllContractAddresses(network string) map[string]string {
	addresses := make(map[string]string)
	
	contracts := []string{
		ProcessRegistryContract,
		OrganizationRegistryContract,
		StateTransitionVerifierGroth16Contract,
		ResultsVerifierGroth16Contract,
		SequencerRegistryContract,
	}
	
	for _, contract := range contracts {
		if addr := GetContractAddress(contract, network); addr != "" && addr != "0x0" {
			addresses[contract] = addr
		}
	}
	
	return addresses
}

// GetSepoliaAddresses returns all contract addresses for Sepolia network
func GetSepoliaAddresses() map[string]string {
	return GetAllContractAddresses(SepoliaNetwork)
}

// GetUzhAddresses returns all contract addresses for UZH network
func GetUzhAddresses() map[string]string {
	return GetAllContractAddresses(UzhNetwork)
}

// GetMainnetAddresses returns all contract addresses for Mainnet network
func GetMainnetAddresses() map[string]string {
	return GetAllContractAddresses(MainnetNetwork)
}
