package contracts

// This file is auto-generated by helpers/write_contract_addresses.sh
// Do not edit manually - run the script to regenerate

// Network constants
const (
	SepoliaNetwork = "sepolia"
	UzhNetwork     = "uzh"
	MainnetNetwork = "mainnet"
	BaseNetwork    = "base"
	CeloNetwork    = "celo"
	TestNetwork    = "test"
)

// AvailableNetworksByName contains the list of networks where Davinci is deployed.
var AvailableNetworksByName = map[string]uint32{
	SepoliaNetwork: 11155111,
	UzhNetwork:     710,
	CeloNetwork:    42220,
	MainnetNetwork: 1,
	BaseNetwork:    8453,
	TestNetwork:    1337, // Local test network
}

// AvailableNetworksByID contains the list of networks where Davinci is deployed.
var AvailableNetworksByID = map[uint32]string{
	11155111: SepoliaNetwork,
	710:      UzhNetwork,
	42220:    CeloNetwork,
	1:        MainnetNetwork,
	8453:     BaseNetwork,
	1337:     TestNetwork,
}

// Contract name constants
const (
	ProcessRegistryContract                = "processRegistry"
	StateTransitionVerifierGroth16Contract = "stateTransitionVerifierGroth16"
	ResultsVerifierGroth16Contract         = "resultsVerifierGroth16"
	SequencerRegistryContract              = "sequencerRegistry"
)

// Dummy consts until we deploy on Mainnet and develop SequencerRegistry
const (
	ProcessRegistryMainnetAddress = "0x0"
	ResultsVerifierGroth16MainnetAddress = "0x0"
	SequencerRegistryBaseAddress = "0x0"
	SequencerRegistryCeloAddress = "0x0"
	SequencerRegistryMainnetAddress = "0x0"
	SequencerRegistrySepoliaAddress = "0x0"
	SequencerRegistryUzhAddress = "0x0"
	StateTransitionVerifierGroth16MainnetAddress = "0x0"
)

// Contract addresses by network
const (
	OrganizationRegistryBaseAddress = "0x9456a7c17bb3b4ed353c03bcb6c493cdb302d559"
	OrganizationRegistryUzhAddress = "0xf7bce4546805547be526ca864d6722ed193e51aa"
	ProcessRegistryBaseAddress = "0x14943da059af3ba4b2f0e26293fca848b15c5235"
	ProcessRegistryCeloAddress = "0xb4c42ee65b123e7717eab8467e9765d9ebe3ad35"
	ProcessRegistrySepoliaAddress = "0x6551971332b6e57c1f5a595a5293ddf7e2a9ad92"
	ProcessRegistryUzhAddress = "0x69b16f67bd2fb18bd720379e9c1ef5ead3872d67"
	ResultsVerifierGroth16BaseAddress = "0x5d84161a1258daa19889ce8a99e224d597dd3de0"
	ResultsVerifierGroth16CeloAddress = "0x76c758b22b06c095e7b32fc7abd1d9c7078da3f1"
	ResultsVerifierGroth16SepoliaAddress = "0x517cb7586e88ed79f00930fc1fb52818e4179c59"
	ResultsVerifierGroth16UzhAddress = "0x00c7f87731346f592197e49a90ad6ec236ad9985"
	StateTransitionVerifierGroth16BaseAddress = "0xdcec7a689e778befbc1ac6cbc17eab81a9ab72e0"
	StateTransitionVerifierGroth16CeloAddress = "0x0da837a0fe67630f6aba2bb070b3eb8d1897f937"
	StateTransitionVerifierGroth16SepoliaAddress = "0x2787011f86043b234e17aa1c41948f2502c380be"
	StateTransitionVerifierGroth16UzhAddress = "0x5e4673cd378f05cc3ae25804539c91e711548741"
)

// GetContractAddress returns the address for a given contract and network
func GetContractAddress(contract, network string) string {
	switch contract {
	case ProcessRegistryContract:
		switch network {
		case SepoliaNetwork:
			return ProcessRegistrySepoliaAddress
		case UzhNetwork:
			return ProcessRegistryUzhAddress
		case MainnetNetwork:
			return ProcessRegistryMainnetAddress
		case BaseNetwork:
			return ProcessRegistryBaseAddress
		case CeloNetwork:
			return ProcessRegistryCeloAddress
		}
	case StateTransitionVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return StateTransitionVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return StateTransitionVerifierGroth16UzhAddress
		case MainnetNetwork:
			return StateTransitionVerifierGroth16MainnetAddress
		case BaseNetwork:
			return StateTransitionVerifierGroth16BaseAddress
		case CeloNetwork:
			return StateTransitionVerifierGroth16CeloAddress
		}
	case ResultsVerifierGroth16Contract:
		switch network {
		case SepoliaNetwork:
			return ResultsVerifierGroth16SepoliaAddress
		case UzhNetwork:
			return ResultsVerifierGroth16UzhAddress
		case MainnetNetwork:
			return ResultsVerifierGroth16MainnetAddress
		case BaseNetwork:
			return ResultsVerifierGroth16BaseAddress
		case CeloNetwork:
			return ResultsVerifierGroth16CeloAddress
		}
	case SequencerRegistryContract:
		switch network {
		case SepoliaNetwork:
			return SequencerRegistrySepoliaAddress
		case UzhNetwork:
			return SequencerRegistryUzhAddress
		case MainnetNetwork:
			return SequencerRegistryMainnetAddress
		case BaseNetwork:
			return SequencerRegistryBaseAddress
		case CeloNetwork:
			return SequencerRegistryCeloAddress
		}
	}
	return ""
}

// GetAllContractAddresses returns a map of all contract addresses for a given network
func GetAllContractAddresses(network string) map[string]string {
	addresses := make(map[string]string)

	contracts := []string{
		ProcessRegistryContract,
		StateTransitionVerifierGroth16Contract,
		ResultsVerifierGroth16Contract,
		SequencerRegistryContract,
	}

	for _, contract := range contracts {
		if addr := GetContractAddress(contract, network); addr != "" && addr != "0x0" {
			addresses[contract] = addr
		}
	}

	return addresses
}

// GetSepoliaAddresses returns all contract addresses for Sepolia network
func GetSepoliaAddresses() map[string]string {
	return GetAllContractAddresses(SepoliaNetwork)
}

// GetUzhAddresses returns all contract addresses for UZH network
func GetUzhAddresses() map[string]string {
	return GetAllContractAddresses(UzhNetwork)
}

// GetMainnetAddresses returns all contract addresses for Mainnet network
func GetMainnetAddresses() map[string]string {
	return GetAllContractAddresses(MainnetNetwork)
}

// GetBaseAddresses returns all contract addresses for Base network
func GetBaseAddresses() map[string]string {
	return GetAllContractAddresses(BaseNetwork)
}

// GetCeloAddresses returns all contract addresses for Celo network
func GetCeloAddresses() map[string]string {
	return GetAllContractAddresses(CeloNetwork)
}
