/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace DKGTypes {
  export type CombinedDecryptionRecordStruct = {
    ciphertextIndex: BigNumberish;
    completed: boolean;
    plaintext: BigNumberish;
  };

  export type CombinedDecryptionRecordStructOutput = [
    ciphertextIndex: bigint,
    completed: boolean,
    plaintext: bigint
  ] & { ciphertextIndex: bigint; completed: boolean; plaintext: bigint };
}

export interface IDKGManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EPOCH_PREFIX"
      | "appManager"
      | "epochNonce"
      | "getAppPoolIndex"
      | "getCombinedDecryption"
      | "getPoolKey"
      | "getPoolStatus"
      | "submitCiphertext"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EPOCH_PREFIX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAppPoolIndex",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCombinedDecryption",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolKey",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCiphertext",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "EPOCH_PREFIX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAppPoolIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCombinedDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoolKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitCiphertext",
    data: BytesLike
  ): Result;
}

export interface IDKGManager extends BaseContract {
  connect(runner?: ContractRunner | null): IDKGManager;
  waitForDeployment(): Promise<this>;

  interface: IDKGManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EPOCH_PREFIX: TypedContractMethod<[], [bigint], "view">;

  appManager: TypedContractMethod<[], [string], "view">;

  epochNonce: TypedContractMethod<[], [bigint], "view">;

  getAppPoolIndex: TypedContractMethod<
    [epochId: BytesLike, aid: BytesLike],
    [bigint],
    "view"
  >;

  getCombinedDecryption: TypedContractMethod<
    [epochId: BytesLike, aid: BytesLike, ciphertextIndex: BigNumberish],
    [DKGTypes.CombinedDecryptionRecordStructOutput],
    "view"
  >;

  getPoolKey: TypedContractMethod<
    [epochId: BytesLike, keyIndex: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "view"
  >;

  getPoolStatus: TypedContractMethod<[epochId: BytesLike], [bigint], "view">;

  submitCiphertext: TypedContractMethod<
    [
      epochId: BytesLike,
      aid: BytesLike,
      c1x: BigNumberish,
      c1y: BigNumberish,
      c2x: BigNumberish,
      c2y: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EPOCH_PREFIX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "appManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "epochNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAppPoolIndex"
  ): TypedContractMethod<
    [epochId: BytesLike, aid: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCombinedDecryption"
  ): TypedContractMethod<
    [epochId: BytesLike, aid: BytesLike, ciphertextIndex: BigNumberish],
    [DKGTypes.CombinedDecryptionRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolKey"
  ): TypedContractMethod<
    [epochId: BytesLike, keyIndex: BigNumberish],
    [[bigint, bigint] & { x: bigint; y: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolStatus"
  ): TypedContractMethod<[epochId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitCiphertext"
  ): TypedContractMethod<
    [
      epochId: BytesLike,
      aid: BytesLike,
      c1x: BigNumberish,
      c1y: BigNumberish,
      c2x: BigNumberish,
      c2y: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
