/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDKGManager,
  IDKGManagerInterface,
} from "../../../../src/interfaces/dkg/IDKGManager";

const _abi = [
  {
    inputs: [],
    name: "CiphertextAlreadySubmitted",
    type: "error",
  },
  {
    inputs: [],
    name: "DecryptionLimitReached",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidCiphertext",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidEpoch",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidPhase",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidProofInput",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolExhausted",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "EPOCH_PREFIX",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "appManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "epochNonce",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes12",
        name: "epochId",
        type: "bytes12",
      },
      {
        internalType: "bytes32",
        name: "aid",
        type: "bytes32",
      },
    ],
    name: "getAppPoolIndex",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes12",
        name: "epochId",
        type: "bytes12",
      },
      {
        internalType: "bytes32",
        name: "aid",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "ciphertextIndex",
        type: "uint16",
      },
    ],
    name: "getCombinedDecryption",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "ciphertextIndex",
            type: "uint16",
          },
          {
            internalType: "bool",
            name: "completed",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "plaintext",
            type: "uint256",
          },
        ],
        internalType: "struct DKGTypes.CombinedDecryptionRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes12",
        name: "epochId",
        type: "bytes12",
      },
      {
        internalType: "uint8",
        name: "keyIndex",
        type: "uint8",
      },
    ],
    name: "getPoolKey",
    outputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes12",
        name: "epochId",
        type: "bytes12",
      },
    ],
    name: "getPoolStatus",
    outputs: [
      {
        internalType: "uint8",
        name: "nextIndex",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes12",
        name: "epochId",
        type: "bytes12",
      },
      {
        internalType: "bytes32",
        name: "aid",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "c1x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c1y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c2x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "c2y",
        type: "uint256",
      },
    ],
    name: "submitCiphertext",
    outputs: [
      {
        internalType: "uint16",
        name: "ciphertextIndex",
        type: "uint16",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDKGManager__factory {
  static readonly abi = _abi;
  static createInterface(): IDKGManagerInterface {
    return new Interface(_abi) as IDKGManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDKGManager {
    return new Contract(address, _abi, runner) as unknown as IDKGManager;
  }
}
