/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICouncilManager } from "./ICouncilManager";
export type { ICouncilManagerErrors } from "./ICouncilManagerErrors";
