/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICensus__factory } from "./ICensus__factory";
export { IOrganizationRegistry__factory } from "./IOrganizationRegistry__factory";
export { IProcessRegistry__factory } from "./IProcessRegistry__factory";
export { IZKVerifier__factory } from "./IZKVerifier__factory";
