/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICensusValidatorInterface extends Interface {
  getFunction(
    nameOrSignature: "getCensusRoot" | "getRootBlockNumber"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCensusRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRootBlockNumber",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCensusRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRootBlockNumber",
    data: BytesLike
  ): Result;
}

export interface ICensusValidator extends BaseContract {
  connect(runner?: ContractRunner | null): ICensusValidator;
  waitForDeployment(): Promise<this>;

  interface: ICensusValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCensusRoot: TypedContractMethod<[], [bigint], "view">;

  getRootBlockNumber: TypedContractMethod<
    [root: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCensusRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRootBlockNumber"
  ): TypedContractMethod<[root: BigNumberish], [bigint], "view">;

  filters: {};
}
