/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DAVINCITypes {
  export type BallotModeStruct = {
    uniqueValues: boolean;
    numFields: BigNumberish;
    groupSize: BigNumberish;
    costExponent: BigNumberish;
    maxValue: BigNumberish;
    minValue: BigNumberish;
    maxValueSum: BigNumberish;
    minValueSum: BigNumberish;
  };

  export type BallotModeStructOutput = [
    uniqueValues: boolean,
    numFields: bigint,
    groupSize: bigint,
    costExponent: bigint,
    maxValue: bigint,
    minValue: bigint,
    maxValueSum: bigint,
    minValueSum: bigint
  ] & {
    uniqueValues: boolean;
    numFields: bigint;
    groupSize: bigint;
    costExponent: bigint;
    maxValue: bigint;
    minValue: bigint;
    maxValueSum: bigint;
    minValueSum: bigint;
  };

  export type EncryptionKeyStruct = { x: BigNumberish; y: BigNumberish };

  export type EncryptionKeyStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };

  export type CensusStruct = {
    censusOrigin: BigNumberish;
    censusRoot: BytesLike;
    contractAddress: AddressLike;
    censusURI: string;
    onchainAllowAnyValidRoot: boolean;
  };

  export type CensusStructOutput = [
    censusOrigin: bigint,
    censusRoot: string,
    contractAddress: string,
    censusURI: string,
    onchainAllowAnyValidRoot: boolean
  ] & {
    censusOrigin: bigint;
    censusRoot: string;
    contractAddress: string;
    censusURI: string;
    onchainAllowAnyValidRoot: boolean;
  };

  export type ProcessStruct = {
    status: BigNumberish;
    organizationId: AddressLike;
    encryptionKey: DAVINCITypes.EncryptionKeyStruct;
    latestStateRoot: BytesLike;
    result: BigNumberish[];
    startTime: BigNumberish;
    duration: BigNumberish;
    maxVoters: BigNumberish;
    votersCount: BigNumberish;
    overwrittenVotesCount: BigNumberish;
    creationBlock: BigNumberish;
    batchNumber: BigNumberish;
    metadataURI: string;
    metadataHash: BytesLike;
    ballotMode: DAVINCITypes.BallotModeStruct;
    census: DAVINCITypes.CensusStruct;
    keyMode: BigNumberish;
    dkgEpochId: BytesLike;
    dkgFirstIndex: BigNumberish;
    dkgCount: BigNumberish;
    dkgZeroSkipped: BigNumberish;
    dkgResultsRequested: boolean;
    dkgAid: BytesLike;
    grace: BigNumberish;
    lastVoteAt: BigNumberish;
  };

  export type ProcessStructOutput = [
    status: bigint,
    organizationId: string,
    encryptionKey: DAVINCITypes.EncryptionKeyStructOutput,
    latestStateRoot: string,
    result: bigint[],
    startTime: bigint,
    duration: bigint,
    maxVoters: bigint,
    votersCount: bigint,
    overwrittenVotesCount: bigint,
    creationBlock: bigint,
    batchNumber: bigint,
    metadataURI: string,
    metadataHash: string,
    ballotMode: DAVINCITypes.BallotModeStructOutput,
    census: DAVINCITypes.CensusStructOutput,
    keyMode: bigint,
    dkgEpochId: string,
    dkgFirstIndex: bigint,
    dkgCount: bigint,
    dkgZeroSkipped: bigint,
    dkgResultsRequested: boolean,
    dkgAid: string,
    grace: bigint,
    lastVoteAt: bigint
  ] & {
    status: bigint;
    organizationId: string;
    encryptionKey: DAVINCITypes.EncryptionKeyStructOutput;
    latestStateRoot: string;
    result: bigint[];
    startTime: bigint;
    duration: bigint;
    maxVoters: bigint;
    votersCount: bigint;
    overwrittenVotesCount: bigint;
    creationBlock: bigint;
    batchNumber: bigint;
    metadataURI: string;
    metadataHash: string;
    ballotMode: DAVINCITypes.BallotModeStructOutput;
    census: DAVINCITypes.CensusStructOutput;
    keyMode: bigint;
    dkgEpochId: string;
    dkgFirstIndex: bigint;
    dkgCount: bigint;
    dkgZeroSkipped: bigint;
    dkgResultsRequested: boolean;
    dkgAid: string;
    grace: bigint;
    lastVoteAt: bigint;
  };

  export type DKGParamsStruct = {
    mode: BigNumberish;
    epochId: BytesLike;
    orgPKx: BigNumberish;
    orgPKy: BigNumberish;
    popAx: BigNumberish;
    popAy: BigNumberish;
    popZ: BigNumberish;
  };

  export type DKGParamsStructOutput = [
    mode: bigint,
    epochId: string,
    orgPKx: bigint,
    orgPKy: bigint,
    popAx: bigint,
    popAy: bigint,
    popZ: bigint
  ] & {
    mode: bigint;
    epochId: string;
    orgPKx: bigint;
    orgPKy: bigint;
    popAx: bigint;
    popAy: bigint;
    popZ: bigint;
  };
}

export interface IProcessRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aidFor"
      | "defaultGrace"
      | "dkgAdapter"
      | "finalizeResultsFromDKG"
      | "genesisRoot"
      | "getNextProcessId"
      | "getProcess"
      | "getProcessEndTime"
      | "getProcessGraceEnd"
      | "getRVerifierVKeyHash"
      | "getSTVerifierVKeyHash"
      | "graceCeil"
      | "graceFloor"
      | "graceMaxTotal"
      | "newProcess"
      | "noticeMin"
      | "requestResultsDecryption"
      | "revealProcessKey"
      | "setProcessCensus"
      | "setProcessDuration"
      | "setProcessGrace"
      | "setProcessMaxVoters"
      | "setProcessMetadata"
      | "setProcessResults"
      | "setProcessStatus"
      | "submitStateTransition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CensusUpdated"
      | "ProcessCreated"
      | "ProcessDurationChanged"
      | "ProcessGraceChanged"
      | "ProcessMaxVotersChanged"
      | "ProcessMetadataUpdated"
      | "ProcessResultsSet"
      | "ProcessStateTransitioned"
      | "ProcessStatusChanged"
      | "ResultsDecryptionRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "aidFor", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "defaultGrace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dkgAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResultsFromDKG",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisRoot",
    values: [
      BytesLike,
      DAVINCITypes.BallotModeStruct,
      DAVINCITypes.EncryptionKeyStruct,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextProcessId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcessEndTime",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcessGraceEnd",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRVerifierVKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSTVerifierVKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "graceCeil", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "graceFloor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "graceMaxTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newProcess",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      DAVINCITypes.BallotModeStruct,
      DAVINCITypes.CensusStruct,
      string,
      BytesLike,
      DAVINCITypes.EncryptionKeyStruct,
      DAVINCITypes.DKGParamsStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "noticeMin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestResultsDecryption",
    values: [BytesLike, BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revealProcessKey",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessCensus",
    values: [BytesLike, DAVINCITypes.CensusStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessDuration",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessGrace",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessMaxVoters",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessMetadata",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessResults",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitStateTransition",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "aidFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultGrace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dkgAdapter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResultsFromDKG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genesisRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextProcessId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProcess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProcessEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProcessGraceEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRVerifierVKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSTVerifierVKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "graceCeil", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "graceFloor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "graceMaxTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newProcess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noticeMin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestResultsDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealProcessKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessCensus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessGrace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessMaxVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitStateTransition",
    data: BytesLike
  ): Result;
}

export namespace CensusUpdatedEvent {
  export type InputTuple = [
    processId: BytesLike,
    censusRoot: BytesLike,
    censusURI: string
  ];
  export type OutputTuple = [
    processId: string,
    censusRoot: string,
    censusURI: string
  ];
  export interface OutputObject {
    processId: string;
    censusRoot: string;
    censusURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessCreatedEvent {
  export type InputTuple = [processId: BytesLike, creator: AddressLike];
  export type OutputTuple = [processId: string, creator: string];
  export interface OutputObject {
    processId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessDurationChangedEvent {
  export type InputTuple = [processId: BytesLike, duration: BigNumberish];
  export type OutputTuple = [processId: string, duration: bigint];
  export interface OutputObject {
    processId: string;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessGraceChangedEvent {
  export type InputTuple = [processId: BytesLike, grace: BigNumberish];
  export type OutputTuple = [processId: string, grace: bigint];
  export interface OutputObject {
    processId: string;
    grace: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessMaxVotersChangedEvent {
  export type InputTuple = [processId: BytesLike, maxVoters: BigNumberish];
  export type OutputTuple = [processId: string, maxVoters: bigint];
  export interface OutputObject {
    processId: string;
    maxVoters: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessMetadataUpdatedEvent {
  export type InputTuple = [
    processId: BytesLike,
    metadataURI: string,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    processId: string,
    metadataURI: string,
    metadataHash: string
  ];
  export interface OutputObject {
    processId: string;
    metadataURI: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessResultsSetEvent {
  export type InputTuple = [
    processId: BytesLike,
    sender: AddressLike,
    result: BigNumberish[]
  ];
  export type OutputTuple = [
    processId: string,
    sender: string,
    result: bigint[]
  ];
  export interface OutputObject {
    processId: string;
    sender: string;
    result: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessStateTransitionedEvent {
  export type InputTuple = [
    processId: BytesLike,
    sender: AddressLike,
    oldStateRoot: BytesLike,
    newStateRoot: BytesLike,
    newVotersCount: BigNumberish,
    newOverwrittenVotesCount: BigNumberish,
    nBlobs: BigNumberish
  ];
  export type OutputTuple = [
    processId: string,
    sender: string,
    oldStateRoot: string,
    newStateRoot: string,
    newVotersCount: bigint,
    newOverwrittenVotesCount: bigint,
    nBlobs: bigint
  ];
  export interface OutputObject {
    processId: string;
    sender: string;
    oldStateRoot: string;
    newStateRoot: string;
    newVotersCount: bigint;
    newOverwrittenVotesCount: bigint;
    nBlobs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessStatusChangedEvent {
  export type InputTuple = [
    processId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    processId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    processId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultsDecryptionRequestedEvent {
  export type InputTuple = [
    processId: BytesLike,
    epochId: BytesLike,
    aid: BytesLike,
    firstIndex: BigNumberish,
    count: BigNumberish
  ];
  export type OutputTuple = [
    processId: string,
    epochId: string,
    aid: string,
    firstIndex: bigint,
    count: bigint
  ];
  export interface OutputObject {
    processId: string;
    epochId: string;
    aid: string;
    firstIndex: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IProcessRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IProcessRegistry;
  waitForDeployment(): Promise<this>;

  interface: IProcessRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aidFor: TypedContractMethod<[processId: BytesLike], [string], "view">;

  defaultGrace: TypedContractMethod<[], [bigint], "view">;

  dkgAdapter: TypedContractMethod<[], [string], "view">;

  finalizeResultsFromDKG: TypedContractMethod<
    [processId: BytesLike],
    [void],
    "nonpayable"
  >;

  genesisRoot: TypedContractMethod<
    [
      processId: BytesLike,
      ballotMode: DAVINCITypes.BallotModeStruct,
      encryptionKey: DAVINCITypes.EncryptionKeyStruct,
      censusOrigin: BigNumberish
    ],
    [string],
    "view"
  >;

  getNextProcessId: TypedContractMethod<
    [organizationId: AddressLike],
    [string],
    "view"
  >;

  getProcess: TypedContractMethod<
    [processId: BytesLike],
    [DAVINCITypes.ProcessStructOutput],
    "view"
  >;

  getProcessEndTime: TypedContractMethod<
    [processId: BytesLike],
    [bigint],
    "view"
  >;

  getProcessGraceEnd: TypedContractMethod<
    [processId: BytesLike],
    [bigint],
    "view"
  >;

  getRVerifierVKeyHash: TypedContractMethod<[], [string], "view">;

  getSTVerifierVKeyHash: TypedContractMethod<[], [string], "view">;

  graceCeil: TypedContractMethod<[], [bigint], "view">;

  graceFloor: TypedContractMethod<[], [bigint], "view">;

  graceMaxTotal: TypedContractMethod<[], [bigint], "view">;

  newProcess: TypedContractMethod<
    [
      status: BigNumberish,
      startTime: BigNumberish,
      duration: BigNumberish,
      maxVoters: BigNumberish,
      ballotMode: DAVINCITypes.BallotModeStruct,
      census: DAVINCITypes.CensusStruct,
      metadataURI: string,
      metadataHash: BytesLike,
      encryptionKey: DAVINCITypes.EncryptionKeyStruct,
      dkg: DAVINCITypes.DKGParamsStruct
    ],
    [string],
    "nonpayable"
  >;

  noticeMin: TypedContractMethod<[], [bigint], "view">;

  requestResultsDecryption: TypedContractMethod<
    [processId: BytesLike, accumulator: BigNumberish[], siblings: BytesLike[]],
    [void],
    "nonpayable"
  >;

  revealProcessKey: TypedContractMethod<
    [processId: BytesLike, sk: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProcessCensus: TypedContractMethod<
    [processId: BytesLike, census: DAVINCITypes.CensusStruct],
    [void],
    "nonpayable"
  >;

  setProcessDuration: TypedContractMethod<
    [processId: BytesLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProcessGrace: TypedContractMethod<
    [processId: BytesLike, grace: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProcessMaxVoters: TypedContractMethod<
    [processId: BytesLike, maxVoters: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProcessMetadata: TypedContractMethod<
    [processId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setProcessResults: TypedContractMethod<
    [processId: BytesLike, publicValues: BytesLike, proofBytes: BytesLike],
    [void],
    "nonpayable"
  >;

  setProcessStatus: TypedContractMethod<
    [processId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitStateTransition: TypedContractMethod<
    [
      processId: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      commitments: BytesLike[],
      ys: BytesLike[],
      kzgProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aidFor"
  ): TypedContractMethod<[processId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "defaultGrace"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dkgAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeResultsFromDKG"
  ): TypedContractMethod<[processId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "genesisRoot"
  ): TypedContractMethod<
    [
      processId: BytesLike,
      ballotMode: DAVINCITypes.BallotModeStruct,
      encryptionKey: DAVINCITypes.EncryptionKeyStruct,
      censusOrigin: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextProcessId"
  ): TypedContractMethod<[organizationId: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getProcess"
  ): TypedContractMethod<
    [processId: BytesLike],
    [DAVINCITypes.ProcessStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProcessEndTime"
  ): TypedContractMethod<[processId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProcessGraceEnd"
  ): TypedContractMethod<[processId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRVerifierVKeyHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSTVerifierVKeyHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "graceCeil"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "graceFloor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "graceMaxTotal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "newProcess"
  ): TypedContractMethod<
    [
      status: BigNumberish,
      startTime: BigNumberish,
      duration: BigNumberish,
      maxVoters: BigNumberish,
      ballotMode: DAVINCITypes.BallotModeStruct,
      census: DAVINCITypes.CensusStruct,
      metadataURI: string,
      metadataHash: BytesLike,
      encryptionKey: DAVINCITypes.EncryptionKeyStruct,
      dkg: DAVINCITypes.DKGParamsStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "noticeMin"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestResultsDecryption"
  ): TypedContractMethod<
    [processId: BytesLike, accumulator: BigNumberish[], siblings: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealProcessKey"
  ): TypedContractMethod<
    [processId: BytesLike, sk: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessCensus"
  ): TypedContractMethod<
    [processId: BytesLike, census: DAVINCITypes.CensusStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessDuration"
  ): TypedContractMethod<
    [processId: BytesLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessGrace"
  ): TypedContractMethod<
    [processId: BytesLike, grace: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessMaxVoters"
  ): TypedContractMethod<
    [processId: BytesLike, maxVoters: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessMetadata"
  ): TypedContractMethod<
    [processId: BytesLike, metadataURI: string, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessResults"
  ): TypedContractMethod<
    [processId: BytesLike, publicValues: BytesLike, proofBytes: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessStatus"
  ): TypedContractMethod<
    [processId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitStateTransition"
  ): TypedContractMethod<
    [
      processId: BytesLike,
      publicValues: BytesLike,
      proofBytes: BytesLike,
      commitments: BytesLike[],
      ys: BytesLike[],
      kzgProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CensusUpdated"
  ): TypedContractEvent<
    CensusUpdatedEvent.InputTuple,
    CensusUpdatedEvent.OutputTuple,
    CensusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessCreated"
  ): TypedContractEvent<
    ProcessCreatedEvent.InputTuple,
    ProcessCreatedEvent.OutputTuple,
    ProcessCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessDurationChanged"
  ): TypedContractEvent<
    ProcessDurationChangedEvent.InputTuple,
    ProcessDurationChangedEvent.OutputTuple,
    ProcessDurationChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessGraceChanged"
  ): TypedContractEvent<
    ProcessGraceChangedEvent.InputTuple,
    ProcessGraceChangedEvent.OutputTuple,
    ProcessGraceChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessMaxVotersChanged"
  ): TypedContractEvent<
    ProcessMaxVotersChangedEvent.InputTuple,
    ProcessMaxVotersChangedEvent.OutputTuple,
    ProcessMaxVotersChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessMetadataUpdated"
  ): TypedContractEvent<
    ProcessMetadataUpdatedEvent.InputTuple,
    ProcessMetadataUpdatedEvent.OutputTuple,
    ProcessMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessResultsSet"
  ): TypedContractEvent<
    ProcessResultsSetEvent.InputTuple,
    ProcessResultsSetEvent.OutputTuple,
    ProcessResultsSetEvent.OutputObject
  >;
  getEvent(
    key: "ProcessStateTransitioned"
  ): TypedContractEvent<
    ProcessStateTransitionedEvent.InputTuple,
    ProcessStateTransitionedEvent.OutputTuple,
    ProcessStateTransitionedEvent.OutputObject
  >;
  getEvent(
    key: "ProcessStatusChanged"
  ): TypedContractEvent<
    ProcessStatusChangedEvent.InputTuple,
    ProcessStatusChangedEvent.OutputTuple,
    ProcessStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ResultsDecryptionRequested"
  ): TypedContractEvent<
    ResultsDecryptionRequestedEvent.InputTuple,
    ResultsDecryptionRequestedEvent.OutputTuple,
    ResultsDecryptionRequestedEvent.OutputObject
  >;

  filters: {
    "CensusUpdated(bytes31,bytes32,string)": TypedContractEvent<
      CensusUpdatedEvent.InputTuple,
      CensusUpdatedEvent.OutputTuple,
      CensusUpdatedEvent.OutputObject
    >;
    CensusUpdated: TypedContractEvent<
      CensusUpdatedEvent.InputTuple,
      CensusUpdatedEvent.OutputTuple,
      CensusUpdatedEvent.OutputObject
    >;

    "ProcessCreated(bytes31,address)": TypedContractEvent<
      ProcessCreatedEvent.InputTuple,
      ProcessCreatedEvent.OutputTuple,
      ProcessCreatedEvent.OutputObject
    >;
    ProcessCreated: TypedContractEvent<
      ProcessCreatedEvent.InputTuple,
      ProcessCreatedEvent.OutputTuple,
      ProcessCreatedEvent.OutputObject
    >;

    "ProcessDurationChanged(bytes31,uint256)": TypedContractEvent<
      ProcessDurationChangedEvent.InputTuple,
      ProcessDurationChangedEvent.OutputTuple,
      ProcessDurationChangedEvent.OutputObject
    >;
    ProcessDurationChanged: TypedContractEvent<
      ProcessDurationChangedEvent.InputTuple,
      ProcessDurationChangedEvent.OutputTuple,
      ProcessDurationChangedEvent.OutputObject
    >;

    "ProcessGraceChanged(bytes31,uint32)": TypedContractEvent<
      ProcessGraceChangedEvent.InputTuple,
      ProcessGraceChangedEvent.OutputTuple,
      ProcessGraceChangedEvent.OutputObject
    >;
    ProcessGraceChanged: TypedContractEvent<
      ProcessGraceChangedEvent.InputTuple,
      ProcessGraceChangedEvent.OutputTuple,
      ProcessGraceChangedEvent.OutputObject
    >;

    "ProcessMaxVotersChanged(bytes31,uint256)": TypedContractEvent<
      ProcessMaxVotersChangedEvent.InputTuple,
      ProcessMaxVotersChangedEvent.OutputTuple,
      ProcessMaxVotersChangedEvent.OutputObject
    >;
    ProcessMaxVotersChanged: TypedContractEvent<
      ProcessMaxVotersChangedEvent.InputTuple,
      ProcessMaxVotersChangedEvent.OutputTuple,
      ProcessMaxVotersChangedEvent.OutputObject
    >;

    "ProcessMetadataUpdated(bytes31,string,bytes32)": TypedContractEvent<
      ProcessMetadataUpdatedEvent.InputTuple,
      ProcessMetadataUpdatedEvent.OutputTuple,
      ProcessMetadataUpdatedEvent.OutputObject
    >;
    ProcessMetadataUpdated: TypedContractEvent<
      ProcessMetadataUpdatedEvent.InputTuple,
      ProcessMetadataUpdatedEvent.OutputTuple,
      ProcessMetadataUpdatedEvent.OutputObject
    >;

    "ProcessResultsSet(bytes31,address,uint256[])": TypedContractEvent<
      ProcessResultsSetEvent.InputTuple,
      ProcessResultsSetEvent.OutputTuple,
      ProcessResultsSetEvent.OutputObject
    >;
    ProcessResultsSet: TypedContractEvent<
      ProcessResultsSetEvent.InputTuple,
      ProcessResultsSetEvent.OutputTuple,
      ProcessResultsSetEvent.OutputObject
    >;

    "ProcessStateTransitioned(bytes31,address,bytes32,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ProcessStateTransitionedEvent.InputTuple,
      ProcessStateTransitionedEvent.OutputTuple,
      ProcessStateTransitionedEvent.OutputObject
    >;
    ProcessStateTransitioned: TypedContractEvent<
      ProcessStateTransitionedEvent.InputTuple,
      ProcessStateTransitionedEvent.OutputTuple,
      ProcessStateTransitionedEvent.OutputObject
    >;

    "ProcessStatusChanged(bytes31,uint8,uint8)": TypedContractEvent<
      ProcessStatusChangedEvent.InputTuple,
      ProcessStatusChangedEvent.OutputTuple,
      ProcessStatusChangedEvent.OutputObject
    >;
    ProcessStatusChanged: TypedContractEvent<
      ProcessStatusChangedEvent.InputTuple,
      ProcessStatusChangedEvent.OutputTuple,
      ProcessStatusChangedEvent.OutputObject
    >;

    "ResultsDecryptionRequested(bytes31,bytes12,bytes32,uint16,uint8)": TypedContractEvent<
      ResultsDecryptionRequestedEvent.InputTuple,
      ResultsDecryptionRequestedEvent.OutputTuple,
      ResultsDecryptionRequestedEvent.OutputObject
    >;
    ResultsDecryptionRequested: TypedContractEvent<
      ResultsDecryptionRequestedEvent.InputTuple,
      ResultsDecryptionRequestedEvent.OutputTuple,
      ResultsDecryptionRequestedEvent.OutputObject
    >;
  };
}
